FROM ruby:2.6.3
RUN apt-get update -qq
RUN apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev software-properties-common libffi-dev
RUN apt-get install -y qt5-default libbison-dev libqt5webkit5-dev nodejs npm vim

RUN mkdir /food_and_drink
WORKDIR /food_and_drink

EXPOSE 3000

ADD Gemfile /food_and_drink/Gemfile
ADD Gemfile.lock /food_and_drink/Gemfile.lock
RUN gem install bundler:2.1.4

RUN bundle install

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update
RUN apt-get install -y yarn
